/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesRawQuartzRouteImport } from './routes/categories.raw-quartz'
import { Route as CategoriesQuartzSlabsRouteImport } from './routes/categories.quartz-slabs'
import { Route as CategoriesMarbleAlternativesRouteImport } from './routes/categories.marble-alternatives'
import { Route as ApiMarbleProductsRouteImport } from './routes/api/marble-products'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRawQuartzRoute = CategoriesRawQuartzRouteImport.update({
  id: '/categories/raw-quartz',
  path: '/categories/raw-quartz',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesQuartzSlabsRoute = CategoriesQuartzSlabsRouteImport.update({
  id: '/categories/quartz-slabs',
  path: '/categories/quartz-slabs',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesMarbleAlternativesRoute =
  CategoriesMarbleAlternativesRouteImport.update({
    id: '/categories/marble-alternatives',
    path: '/categories/marble-alternatives',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMarbleProductsRoute = ApiMarbleProductsRouteImport.update({
  id: '/api/marble-products',
  path: '/api/marble-products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/api/marble-products': typeof ApiMarbleProductsRoute
  '/categories/marble-alternatives': typeof CategoriesMarbleAlternativesRoute
  '/categories/quartz-slabs': typeof CategoriesQuartzSlabsRoute
  '/categories/raw-quartz': typeof CategoriesRawQuartzRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/api/marble-products': typeof ApiMarbleProductsRoute
  '/categories/marble-alternatives': typeof CategoriesMarbleAlternativesRoute
  '/categories/quartz-slabs': typeof CategoriesQuartzSlabsRoute
  '/categories/raw-quartz': typeof CategoriesRawQuartzRoute
  '/categories': typeof CategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/api/marble-products': typeof ApiMarbleProductsRoute
  '/categories/marble-alternatives': typeof CategoriesMarbleAlternativesRoute
  '/categories/quartz-slabs': typeof CategoriesQuartzSlabsRoute
  '/categories/raw-quartz': typeof CategoriesRawQuartzRoute
  '/categories/': typeof CategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/api/marble-products'
    | '/categories/marble-alternatives'
    | '/categories/quartz-slabs'
    | '/categories/raw-quartz'
    | '/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/api/marble-products'
    | '/categories/marble-alternatives'
    | '/categories/quartz-slabs'
    | '/categories/raw-quartz'
    | '/categories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/api/marble-products'
    | '/categories/marble-alternatives'
    | '/categories/quartz-slabs'
    | '/categories/raw-quartz'
    | '/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ApiMarbleProductsRoute: typeof ApiMarbleProductsRoute
  CategoriesMarbleAlternativesRoute: typeof CategoriesMarbleAlternativesRoute
  CategoriesQuartzSlabsRoute: typeof CategoriesQuartzSlabsRoute
  CategoriesRawQuartzRoute: typeof CategoriesRawQuartzRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/raw-quartz': {
      id: '/categories/raw-quartz'
      path: '/categories/raw-quartz'
      fullPath: '/categories/raw-quartz'
      preLoaderRoute: typeof CategoriesRawQuartzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/quartz-slabs': {
      id: '/categories/quartz-slabs'
      path: '/categories/quartz-slabs'
      fullPath: '/categories/quartz-slabs'
      preLoaderRoute: typeof CategoriesQuartzSlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/marble-alternatives': {
      id: '/categories/marble-alternatives'
      path: '/categories/marble-alternatives'
      fullPath: '/categories/marble-alternatives'
      preLoaderRoute: typeof CategoriesMarbleAlternativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marble-products': {
      id: '/api/marble-products'
      path: '/api/marble-products'
      fullPath: '/api/marble-products'
      preLoaderRoute: typeof ApiMarbleProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ApiMarbleProductsRoute: ApiMarbleProductsRoute,
  CategoriesMarbleAlternativesRoute: CategoriesMarbleAlternativesRoute,
  CategoriesQuartzSlabsRoute: CategoriesQuartzSlabsRoute,
  CategoriesRawQuartzRoute: CategoriesRawQuartzRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
